skip-check:
  - CKV_SECRET_6
  - CKV_K8S_21
  - CKV_DOCKER_2
  - CKV_ARGO_2
  # "Ensure Workflow pods are not using the default ServiceAccount."
  #  - Doesn't matter when just running integration tests
  - CKV_ARGO_1
