stages:
  - lint
  - build
  - release

mega-linter:
  stage: lint
  image: megalinter/megalinter-documentation:v5
  script: ["true"] # if script: ["true"] does not work, you may try ->  script: [ "/bin/bash /entrypoint.sh" ]
  variables:
    # All available variables are described in documentation
    # https://megalinter.github.io/configuration/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

# used to check if the docs are able to be build
# final building and publishing is done via GitHub actions
build-docs:
  stage: build
  image: python:3.9
  script:
    - pip install mkdocs-material==8.*
    - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      changes:
        - mkdocs.yml
        - docs/*

create-release:
  image: harbor.miracum.org/miracum-devops/semantic-release:e20333a5
  stage: release
  script:
    - mkdir -p dist/
    - cp -r docker-compose/ dist/docker-compose/
    - tar -C dist -zcvf dist/recruit-docker-compose.tar.gz docker-compose/
    - npx semantic-release
  only:
    - master
