version: "3.7"

services:
  omopdb:
    image: quay.io/miracum/omop:test-data-v3
    restart: unless-stopped

  ohdsi-webapi:
    image: docker.io/ohdsi/webapi:2.11.0
    ports:
      - "127.0.0.1:38089:8080"
    restart: unless-stopped
    cap_drop:
      - ALL
    environment:
      PGHOST: omopdb
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "http://localhost:38084"
    depends_on:
      - omopdb

  ohdsi-atlas:
    image: docker.io/ohdsi/atlas:2.11.0
    ports:
      - "127.0.0.1:38084:8080"
    restart: unless-stopped
    cap_drop:
      - ALL
    environment:
      WEBAPI_URL: "http://localhost:38089/WebAPI/"
    depends_on:
      - ohdsi-webapi

  fhir:
    image: docker.io/hapiproject/hapi:v6.0.1
    restart: unless-stopped
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:38083:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://fhir-db:5432/fhir?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      VALIDATION_REQUESTS_ENABLED: "false"
      HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY: "true"
      HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_DELETE: "false"
      HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_WRITE: "false"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_ALLOW_MULTIPLE_DELETE: "true"
    depends_on:
      - fhir-db

  fhir-db:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  loader:
    image: curlimages/curl:7.83.1
    cap_drop:
      - ALL
    command: >
      -X POST
      -H "Content-Type: application/json"
      --retry-connrefuse
      --connect-timeout 10
      --retry-max-time 0
      --retry 500
      --retry-delay 30
      --data "@/data/sample-cohortdefinition.json"
      http://ohdsi-webapi:8080/WebAPI/cohortdefinition
    volumes:
      - ./staging/sample-cohortdefinition.json:/data/sample-cohortdefinition.json:ro
    depends_on:
      - ohdsi-webapi

  maildev:
    image: maildev/maildev:2.0.5
    restart: unless-stopped
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:38085:1080"

  keycloak:
    image: quay.io/keycloak/keycloak:15.1.1
    restart: unless-stopped
    cap_drop:
      - ALL
    command:
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=singleFile
      - -Dkeycloak.migration.file=/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_STATISTICS: "all"
    volumes:
      - ./staging/aio-export.json:/tmp/realm.json:ro
    ports:
      - "127.0.0.1:38086:8080"

  notify:
    depends_on:
      - fhir
      - maildev

  query:
    depends_on:
      - fhir
      - omopdb
      - ohdsi-webapi

  list:
    depends_on:
      - fhir
