name: "Build Jib container image"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      module-name:
        description: "Name of the project inside the /src/ dir"
        type: string
        required: true
      build-with:
        description: "Name of the tool to build the module with. One of `jib`, `dockerfile`"
        type: string
        required: true
      working-directory:
        description: "Working directory to run `./gradlew build` etc. in"
        type: string
        default: ./src
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.image-meta.outputs.image }}
      digest: ${{ steps.image-meta.outputs.digest }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build using jib
        if: ${{ inputs.build-with == 'jib' }}
        uses: ./.github/actions/build-jib
        with:
          project-name: ${{ inputs.module-name }}

      - name: build using dockerfile
        if: ${{ inputs.build-with == 'dockerfile' }}
        uses: ./.github/actions/build-list

  provenance:
    needs:
      - build
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Use a tagged release once we have one.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0-rc.2
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
      # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Remove after GA release.
      compile-generator: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
