name: "build container image"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      module-name:
        description: "Name of the project inside the /src/ dir"
        type: string
        required: true
      context:
        description: "the docker build context path"
        type: string
        default: .
        required: false
    outputs:
      image-tag:
        description: "The image tag that was built"
        value: ${{ jobs.build.outputs.tag }}

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/${{ inputs.module-name }}

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ env.IMAGE_NAME }}
      digest: ${{ steps.build.outputs.digest }}
      tag: ${{ steps.container_meta.outputs.version }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

      - name: Container meta
        id: container_meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.created=""

      - name: Build image
        id: build
        uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0 # tag=v3.1.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: ${{ steps.container_meta.outputs.tags }}
          labels: ${{ steps.container_meta.outputs.labels }}
          load: true
          context: ${{ inputs.context }}
          build-args: |
            MODULE_NAME=${{ inputs.module-name }}

      - name: Run unit tests
        uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0 # tag=v3.1.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          target: test
          context: ${{ inputs.context }}
          build-args: |
            MODULE_NAME=${{ inputs.module-name }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe # tag=v0.7.1
        with:
          image-ref: ${{ fromJson(steps.container_meta.outputs.json).tags[0] }}
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: "true"

      - name: Save container image as tar archives
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        env:
          IMAGE: ${{ fromJson(steps.container_meta.outputs.json).tags[0] }}
        run: |
          docker save "$IMAGE" -o /tmp/${{ inputs.module-name }}-image.tar

      - name: Upload container image
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: ${{ inputs.module-name }}-build-artifacts
          path: |
            /tmp/${{ inputs.module-name }}-image.tar

  provenance:
    needs:
      - build
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
      # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Remove after GA release.
      compile-generator: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
