name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - module: "query"
            context: "src/"
          - module: "notify"
            context: "src/"
          - module: "list"
            context: "src/list/"
    uses: ./.github/workflows/build.yaml
    with:
      module-name: ${{ matrix.module }}
      context: ${{ matrix.context }}

  test:
    runs-on: ubuntu-22.04
    needs:
      - build
    strategy:
      matrix:
        include:
          - module: "query"
            e2e-test-directory: "tests/e2e/"
          - module: "notify"
            e2e-test-directory: "tests/e2e/"
          # Disabled temporarily
          # - module: "list"
          #   e2e-test-directory: "frontend/tests/e2e/"
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/${{ matrix.module }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - uses: ./.github/actions/test-image
        with:
          project-name: ${{ matrix.module }}
          image-name: ${{ env.IMAGE_NAME }}
          image-tag: ${{ needs.build.outputs.image-tag }}
          e2e-test-directory: ${{ matrix.e2e-test-directory }}

  integration-tests:
    needs:
      - build
      - test
    uses: ./.github/workflows/integration-test.yaml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}

  test-docker-compose:
    # the docker compose image tags only change on releases, so
    # it's sufficient to just run tests then.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - build
      - test
    uses: ./.github/workflows/test-compose-installation.yaml
