name: release

on:
  release:
    types:
      - created

permissions: read-all

jobs:
  prepare-artifacts:
    name: Prepare Artifacts
    runs-on: ubuntu-22.04
    container: ghcr.io/chgl/kube-powertools:v1.22.2@sha256:a8a2649b29be23756d830bb98a5ac71cca515e35886df90b3116293c03bfc0fc
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      # TODO: replace tags with digests in compose - requires waiting for ci/build to be completed
      - name: Build Docker Compose deployment bundle
        run: |
          mkdir -p dist/
          cp -r docker-compose/ dist/
          tar -C dist -zcvf dist/recruit-docker-compose.tar.gz docker-compose/

      - name: Build SBOM bundle from container images
        run: |
          ./.github/generate-sboms.sh
          cp -r sboms/ dist/
          tar -C dist -zcvf dist/recruit-container-sboms.tar.gz sboms/

      - name: Generate SLSA subject for Docker Compose and SBOM bundles
        id: hash
        working-directory: dist
        run: |
          sha256sum recruit-docker-compose.tar.gz recruit-container-sboms.tar.gz > recruit-hashes.sha256
          echo "hashes=$(base64 -w0 < recruit-hashes.sha256)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: release-assets
          path: dist/*.tar.gz

  provenance:
    needs:
      - prepare-artifacts
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    # can't be referenced by digest. See <https://github.com/slsa-framework/slsa-github-generator#verification-of-provenance>
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.prepare-artifacts.outputs.hashes }}"
      compile-generator: true # Workaround for https://github.com/slsa-framework/slsa-github-generator/issues/1163

  upload:
    needs: [provenance]
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          name: "${{ needs.provenance.outputs.attestation-name }}"

      - name: Download docker-compose
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: release-assets

      # TODO: upload helm chart
      - name: upload attestation to release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # tag=v1
        with:
          files: |
            "${{ needs.provenance.outputs.attestation-name }}"
            release-assets/recruit-docker-compose.tar.gz
            release-assets/recruit-container-sboms.tar.gz
